// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NET.Kniaz.ProperArchitecture.Persistence;

#nullable disable

namespace NET.Kniaz.ProperArchitecture.Persistence.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Commit", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<Guid?>("StoryId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("StoryId");
                b.ToTable("Commits");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Currency", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("ShortName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("ValueinUSD").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.ToTable("Currencies");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Project", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("EndWeek").HasColumnType("int");
                b.Property<int>("EndYear").HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("StartWeek").HasColumnType("int");
                b.Property<int>("StartYear").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Projects");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Resource", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<string>("FirstName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("LastName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Resources");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.SimulationResult", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<int>("CommitedPoints").HasColumnType("int");
                b.Property<int>("DeliveredPoints").HasColumnType("int");
                b.Property<int?>("DeveloperEventsImpact").HasColumnType("int");
                b.Property<string>("SimulatorType").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int?>("NumberOfDeveloperEvents").HasColumnType("int");
                b.Property<int>("NumberOfExecutedSprints").HasColumnType("int");
                b.Property<int>("NumberOfPlannedSprints").HasColumnType("int");
                b.Property<int?>("NumberOfScopeEvents").HasColumnType("int");
                b.Property<DateTime>("RunDate").HasColumnType("datetime2");
                b.Property<int?>("ScopeEventsImpact").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("SimulationResults");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Sprint", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<int?>("CommittedPoints").HasColumnType("int");
                b.Property<int?>("DeliveredPoints").HasColumnType("int");
                b.Property<int>("EndWeek").HasColumnType("int");
                b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                b.Property<int>("StartWeek").HasColumnType("int");
                b.Property<Guid>("TeamId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("ProjectId");
                b.HasIndex("TeamId");
                b.ToTable("Sprints");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Story", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int?>("IsDone").HasDefaultValue(0).HasColumnType("int");
                b.Property<int?>("PointValue").HasColumnType("int");
                b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                b.Property<Guid?>("SprintId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("ProjectId");
                b.HasIndex("SprintId");
                b.ToTable("Stories");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Team", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("ProjectId");
                b.ToTable("Teams");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.TeamMember", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<Guid>("CurrencyId").HasColumnType("uniqueidentifier");
                b.Property<int>("EndWeek").HasColumnType("int");
                b.Property<int>("EndYear").HasColumnType("int");
                b.Property<decimal>("HourlyRate").HasPrecision(10, 2).HasColumnType("decimal(10,2)");
                b.Property<Guid>("ResourceId").HasColumnType("uniqueidentifier");
                b.Property<int>("StartWeek").HasColumnType("int");
                b.Property<int>("StartYear").HasColumnType("int");
                b.Property<Guid>("TeamId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("CurrencyId");
                b.HasIndex("ResourceId");
                b.HasIndex("TeamId");
                b.ToTable("TeamMembers");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Commit", b =>
            {
                b.HasOne("NET.Kniaz.ProperArchitecture.Domain.Entities.Story", null)
                    .WithMany("Commits")
                    .HasForeignKey("StoryId");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Sprint", b =>
            {
                b.HasOne("NET.Kniaz.ProperArchitecture.Domain.Entities.Project", null)
                    .WithMany("Sprints")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("NET.Kniaz.ProperArchitecture.Domain.Entities.Team", null)
                    .WithMany()
                    .HasForeignKey("TeamId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Story", b =>
            {
                b.HasOne("NET.Kniaz.ProperArchitecture.Domain.Entities.Project", null)
                    .WithMany("Stories")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("NET.Kniaz.ProperArchitecture.Domain.Entities.Sprint", null)
                    .WithMany("Stories")
                    .HasForeignKey("SprintId");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Team", b =>
            {
                b.HasOne("NET.Kniaz.ProperArchitecture.Domain.Entities.Project", null)
                    .WithMany("Teams")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.TeamMember", b =>
            {
                b.HasOne("NET.Kniaz.ProperArchitecture.Domain.Entities.Currency", "Currency")
                    .WithMany()
                    .HasForeignKey("CurrencyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("NET.Kniaz.ProperArchitecture.Domain.Entities.Resource", "Resource")
                    .WithMany()
                    .HasForeignKey("ResourceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("NET.Kniaz.ProperArchitecture.Domain.Entities.Team", null)
                    .WithMany("TeamMembers")
                    .HasForeignKey("TeamId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Project", b =>
            {
                b.Navigation("Sprints");
                b.Navigation("Stories");
                b.Navigation("Teams");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Sprint", b =>
            {
                b.Navigation("Stories");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Story", b =>
            {
                b.Navigation("Commits");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.Team", b =>
            {
                b.Navigation("TeamMembers");
            });

            modelBuilder.Entity("NET.Kniaz.ProperArchitecture.Domain.Entities.TeamMember", b =>
            {
                b.Navigation("Currency");
                b.Navigation("Resource");
            });
#pragma warning restore 612, 618
        }
    }
}
